### ISSUE TITLE
Extension can't find npm-linthtml 

### ISSUE THREAD

**Issue by Cirieno** [linthtml/vscode-linthtml#432]
Hi.  I'm also having the issue in VSCode/Win/1.96.0 (user) that the extension "can't find global or local @linthtml/linthtml package" -- I installed locally and linthtml works on the command line when I force an error in my page:

```
$ npx linthtml "src/index.html"

Found 1 files
✔ Files analyzed
File: src/index.html
Config file: C:\DEV\...\MAIN\.linthtmlrc.json
 2:1  error  The first element of the document should be <!DOCTYPE>  doctype-first
✖ 1 problem (1 error, 0 warning)
```

I have "C:\Program Files\nodejs\" in my environment vars (but if I didn't I'd have a world of other issues first).

Any thoughts on why the extension isn't picking up the install?

**Comment by KamiKillertO** [comment]
Ok, looks like it's a NodeJS ESM issue on Windows, I've a working fix 👍

**Comment by KamiKillertO** [comment]
I've released a fix, it should works now

**Comment by Cirieno** [comment]
It looks like it's working now, thanks for looking into it!
