### ISSUE TITLE
"warning"/"error" Seems to be not responding

### ISSUE THREAD

**Issue by CVral** [linthtml/vscode-linthtml#55]
I tried playing around the rules with warning but seems it always turns out to be error. Is there a way I could configure linthtmlrc.js so as to show the rules as warning and not error as always.
Ver : 0.4.1
Using VS-Code IDE and linthtml extension: kamikillerto.vscode-linthtml

```
rules: {
            'img-req-alt': [ 'warning' ],
            'img-req-alt': 'warning',
            'tag-req-attr': [
                true,
                {
                    img: [ { name: 'src' }, { name: 'alt' } ],
                    iframe: [ { name: 'title' } ],
                    button: [ { name: 'id' } ]
                }
            ],
            'line-end-style': [
                'warning',
                'lf'
            ]
        }
```
I reported issue on linthtml and got redirected here.
https://github.com/linthtml/linthtml/issues/198#issuecomment-639308319

Any workaround would also be helpful

**Comment by KamiKillertO** [comment]
@CVral I've just released a new version with a fix 😄 .

**Comment by CVral** [comment]
Cheers !!
