### ISSUE TITLE
the path to the .linthtmlrc

### ISSUE THREAD

**Issue by hansnolte** [linthtml/vscode-linthtml#68]
Can someone please explain to me how to include (the path to) the .linthtmlrc.

Is my .linthtmlrc even correct?
If not, please give me a short instruction how to create them correctly.

Many thanks in advance

```
maxerr: false
raw-ignore-regex: false
attr-bans:
  - align
  - background
  - bgcolor
  - border
  - frameborder
  - longdesc
  - marginwidth
  - marginheight
  - scrolling
  - style
  - width
indent-delta: false
indent-style: nonmixed
indent-width: 4
indent-width-cont: false
spec-char-escape: true
text-ignore-regex: false
tag-bans:
  - style
  - b
  - i
tag-close: true
tag-name-lowercase: true
tag-name-match: true
tag-self-close: false
doctype-first: false
doctype-html5: false
attr-name-style: dash
attr-name-ignore-regex: false
attr-no-dup: true
attr-no-unsafe-char: true
attr-order: false
attr-quote-style: double
attr-req-value: true
attr-new-line: false
attr-validate: true
id-no-dup: true
id-class-no-ad: true
id-class-style: underscore
class-no-dup: true
class-style: false
id-class-ignore-regex: false
img-req-alt: true
img-req-src: true
html-valid-content-model: true
head-valid-content-model: true
href-style: false
link-req-noopener: true
label-req-for: true
line-end-style: lf
line-no-trailing-whitespace: true
line-max-len: false
line-max-len-ignore-regex: false
head-req-title: true
title-no-dup: true
title-max-len: 60
html-req-lang: false
lang-style: case
fig-req-figcaption: false
focusable-tabindex-style: false
input-radio-req-name: true
input-req-label: false
table-req-caption: false
table-req-header: false
tag-req-attr: false
```

**Comment by KamiKillertO** [comment]
@hansnolte there's the setting `linthtml.configFile`, if you provide the absolute path to your config file it will work.
About your config file can you copy it again in a [multiline code block](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code)? I'm having a hard reading it.

**Comment by hansnolte** [comment]
Hello  KamiKillertO ,

thank you, It works.
I only had to add NodeJS to the Windows system variables.

And sorry for the mess, I hope the formatting is correct now.

**Comment by viT-1** [comment]
Why I should manually set path to my Windows user directory for global `.linthtmlrc.js` file?
For example eslint and stylelint not need to set paths to their global configurations.

**Comment by KamiKillertO** [comment]
@viT-1 Normally you should not have to provide a path to a config path as long as NodeJs is installed on windows.
